/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Keyboard.gltf --transform 
Files: Keyboard.gltf [3.01MB] > C:\Users\My PC\Downloads\cartoon_mini_keyboard\Keyboard-transformed.glb [296.24KB] (90%)
Author: Matys (https://sketchfab.com/Matysino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-mini-keyboard-79a8ea6311bf48faa10e381263a9beb5
Title: Cartoon Mini Keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LP_keyboard_0.geometry} material={materials.keyboard} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.LP_outline_0.geometry} material={materials.outline} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Keyboard-transformed.glb')
